filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/processo-judicial.json
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "processo-judicial-logs"

setup.template.name: "processo-judicial-logs"
setup.template.pattern: "processo-judicial-logs"
setup.ilm.enabled: false